### ISSUE TITLE
different target OS

### ISSUE THREAD

**Issue by wajeeha77** [intel-iot-devkit/smart-retail-analytics#23]

**Comment by wajeeha77** [comment]
please let me know if the smart-retail-analytics can be used and run on windows machine instead of linux @w4ilun @eashtianjr @IanXSmith @intelcpdp

**Comment by bharath5673** [comment]
| Details           |              |
|-----------------------|---------------|
| Target OS:            |  Ubuntu\* 22.04 LTS   |
|                       |  Ubuntu\* 20.04 LTS   |
|                       |  Ubuntu\* 18.04 LTS   |
|                       |  Windows\* 10 |
|                       |  Windows\* 11 |
| Programming Language: |  Python\* 3.7~3.9 |
| Time to Complete:     |  10-12min     |



@
https://gist.github.com/bharath5673/ec6065adfafef3e0173f31198f98c14a
